### ISSUE TITLE
Wrong parameters in deleteRecipientsSegment

### ISSUE THREAD

**Issue by EdMueller** [newsletter2go/newsletter2go-api-php#17]
The function
public function deleteRecipientsSegment($segmentId, $recipientId, $filter) {
    $endpoint = "/lists/$listId/groups/$segmentId/recipients?_filter=$filter";
    return $this->curl($endpoint, array(), static::METHOD_DELETE);
}
is wrong. Unused variable "$recipientId" and the variable "$listId" is not defined. And what's about "$filter"? And on the way through deleteRecipientsSegment -> curl -> _curl the variable $filter in the $endpoint will be overwritten in _curl?

**Comment by mfrenzel** [comment]
@EdMueller thanks for your input. We fixed these issues now
* [Endpoint](https://github.com/newsletter2go/newsletter2go-api-php/blob/master/src/Newsletter2Go_REST_Api.php#L506)
* [GET-Param](https://github.com/newsletter2go/newsletter2go-api-php/blob/master/src/Newsletter2Go_REST_Api.php#L1247)
