### ISSUE TITLE
Attributes not honored in updateRecipient / updateRecipients

### ISSUE THREAD

**Issue by jaltek** [newsletter2go/newsletter2go-api-php#19]
There is actually no way to set custom attributes via updateRecipient / updateRecipients

**Comment by hirbod** [comment]
And this really is a shame.

**Comment by mfrenzel** [comment]
@jaltek  @Hirbod 
Thank for your feedback.
This project is meant to be a starting point implementation. Feel free to fork from it to add the endpoints you need.
