### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by tbba** [newsletter2go/newsletter2go-api-php#2]
I am missing some simple examples for using the api class.

Simple examples like mimicking a subscription form by sending receiver data for DOI to your address book. Use case:  If a user clicked a "subscribe" checkbox on a php form (a contact form, for example) and the form was submitted.

**Comment by SirDagen** [comment]
Yeah, I added a "how-to-include" file, but it was dismissed. I have no idea why. You can find it here. Hope it helps: 

https://github.com/SirDagen/newsletter2go-api-php/commit/5b179e9b7d156d6afb533b082249a5984493a747

**Comment by tbba** [comment]
GREAT !!!!! Thank you very much !!!!
