### ISSUE TITLE
Add missing management API methods

### ISSUE THREAD

**Issue by bkonetzny** [newsletter2go/newsletter2go-api-php#4]
To use this library as a full featured client to manage newsletters and recipients, the following methods should be added to the PHP SDK:

- Create Lists (POST /lists)
- Add Recipients (POST /recipients)
- Add Test-Recipients to List (POST /lists/{LIST_ID}/testrecipients)
- Send Test-Newsletter (POST /newsletters/{NEWSLETTER_ID}/sendtest)

**Comment by steffenschebesta** [comment]
@bkonetzny please check out our new API docs: http://docs.newsletter2go.com
It contains a Postman collection that makes it really easy to try out all the calls and contains all the missing information.

**Comment by bkonetzny** [comment]
Hi @steffenschebesta,

it's not about missing API docs, but about missing implementation in the SDK. These methods simply do not exist in the PHP SDK - whats the purpose of this SDK if its incomplete and we have to build them by ourself?

**Comment by ghost** [comment]
I agree, that there is quite important functionality missing in the SDK.

**Comment by SirDagen** [comment]
https://github.com/newsletter2go/newsletter2go-api-php/pull/10

**Comment by newsletter2go** [comment]
The endpoints for adding Recipients (provided by @SirDagen ) are now directly added to the API-Client-Class.
