### ISSUE TITLE
Uncatchable warnings, if the credentials fails

### ISSUE THREAD

**Issue by mentor2k1** [newsletter2go/newsletter2go-api-php#8]
if you try to call the API with a wrong password and you catch the exception from ->curl() you will get warnings from getToken, because access_token und refresh_token are not set.

the check should be moved in the near of current line61/62

... Newsletter2Go_REST_Api.php Line:61:core::error(integer(8),string(Undefined property: stdClass::$access_token) ...
... Newsletter2Go_REST_Api.php Line:62:core::error(integer(8),string(Undefined property: stdClass::$refresh_token) ...

**Comment by mfrenzel** [comment]
@mentor2k1 thanks for your input. Unfortunately we were not able to reproduce your issue but tried to solve it anyways.
Let uns know if the new approach is solving your issue or not:
https://github.com/newsletter2go/newsletter2go-api-php/blob/master/src/Newsletter2Go_REST_Api.php#L71
